name: BSK PR Validation
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'Makefile'
      - 'LICENSE'
jobs:
  build:
    name: 'Validate Pull Request Builds'
    runs-on: windows-latest
    env:
      SolutionPath: BeatSaberKeeper.sln
      TestProjectPath: BeatSaberKeeper.Tests/BeatSaberKeeper.Tests.csproj
    steps:
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Restore dependencies
        run: dotnet restore $env:SolutionPath
      - name: Build Solution
        run: dotnet build --no-restore $env:SolutionPath
      - name: Run Tests
        run: dotnet test --no-restore --verbosity normal $env:TestProjectPath
